## Deterministic lossless bibliography merge.
## Precedence: harvested < curated references.bib < hand-authored.bib.
## Raw selected blocks are preserved; only newly harvested keys receive default
## project fields. The validated result is synchronized to book/references.bib.

source("code/R/00-paths.R")
source("code/R/00-bibtex-utils.R")

harvest_file <- file.path(paths$refs, "harvested.bib")
curated_file <- file.path(paths$refs, "references.bib")
hand_file <- file.path(paths$refs, "hand-authored.bib")
idx_file <- file.path(paths$refs, "asset-index.csv")

harvest <- read_bib_blocks(harvest_file)
curated <- read_bib_blocks(curated_file)
hand <- read_bib_blocks(hand_file)
idx <- read.csv(idx_file, stringsAsFactors = FALSE, na.strings = "")

as_map <- function(blocks, label) {
  keys <- vapply(blocks, bib_key_from_block, character(1))
  if (anyNA(keys)) stop(label, " contains an unparseable key")
  if (anyDuplicated(keys)) stop(label, " contains duplicate keys: ",
                                paste(unique(keys[duplicated(keys)]), collapse = ", "))
  setNames(as.list(blocks), keys)
}
hmap <- as_map(harvest, "harvested.bib")
cmap <- as_map(curated, "references.bib")
amap <- as_map(hand, "hand-authored.bib")

## Preserve curated order; append genuinely new hand and harvested keys sorted.
order_keys <- c(names(cmap), sort(setdiff(names(amap), names(cmap))),
                sort(setdiff(names(hmap), union(names(cmap), names(amap)))))

asset_for <- function(key) {
  z <- idx[!is.na(idx$key) & idx$key == key & idx$pdf, , drop = FALSE]
  if (!nrow(z)) return("")
  file.path(basename(libraries[[z$library[1]]]), paste0(z$stem[1], ".pdf"))
}

source_of <- character(length(order_keys)); names(source_of) <- order_keys
out <- lapply(order_keys, function(k) {
  if (k %in% names(amap)) {
    source_of[k] <<- "hand-authored"
    amap[[k]]
  } else if (k %in% names(cmap)) {
    source_of[k] <<- "curated"
    cmap[[k]]
  } else {
    source_of[k] <<- "harvested-new"
    replace_or_add_project_fields(hmap[[k]], asset = asset_for(k))
  }
})

tmp <- tempfile(fileext = ".bib")
merged_lines <- unlist(lapply(out, function(x) c(x, "")))
if (length(merged_lines) && !nzchar(tail(merged_lines, 1L)))
  merged_lines <- head(merged_lines, -1L)
writeLines(c(
  "% refs/references.bib — validated bibliography of record.",
  "% Generated by code/R/02-seed-references.R with precedence:",
  "% harvested < curated < hand-authored. Selected entry blocks are preserved.",
  sprintf("%% %d entries: %d curated, %d hand-authored overrides, %d harvested additions.",
          length(out), sum(source_of == "curated"), sum(source_of == "hand-authored"),
          sum(source_of == "harvested-new")), "",
  merged_lines), tmp)

val <- validate_bib_file(tmp, require_project_fields = TRUE)
if (!val$ok) stop(paste(val$problems, collapse = "\n"))

invisible(file.copy(tmp, curated_file, overwrite = TRUE))
invisible(file.copy(curated_file, file.path(paths$book, "references.bib"), overwrite = TRUE))

merge_report <- data.frame(key = order_keys, selected_from = unname(source_of[order_keys]),
                           md5 = vapply(out, md5_text, character(1)),
                           stringsAsFactors = FALSE)
write.csv(merge_report, file.path(paths$verification, "bibliography-merge.csv"),
          row.names = FALSE)

## Residue list: recursively indexed assets without an embedded BibTeX block.
manual <- idx[!idx$bibtex, c("library", "stem", "pdf", "ocr")]
manual <- manual[!duplicated(paste(manual$library, manual$stem)), ]
write.csv(manual, file.path(paths$refs, "needs-manual-entry.csv"), row.names = FALSE)

cat(sprintf("bibliography merged : %d entries\n", length(out)))
cat(sprintf("  curated retained  : %d\n", sum(source_of == "curated")))
cat(sprintf("  hand overrides    : %d\n", sum(source_of == "hand-authored")))
cat(sprintf("  harvested new     : %d\n", sum(source_of == "harvested-new")))
cat(sprintf("book copy identical : %s\n",
            identical(readBin(curated_file, "raw", file.info(curated_file)$size),
                      readBin(file.path(paths$book, "references.bib"), "raw",
                              file.info(file.path(paths$book, "references.bib"))$size))))
