## 09-figures.R — the canonical figure store.
## Every figure ships an .md caption sidecar written here, so a caption cannot
## drift from the code that made the figure. Chapters embed; they never plot.

source("code/R/00-paths.R")
source("code/R/02-rank-concordance.R")
FIG <- paths$figures
dir.create(FIG, showWarnings = FALSE, recursive = TRUE)

## colour-blind-safe, consistent with the DPMirt package palette
PAL <- c("#0072B2", "#D55E00", "#009E73", "#CC79A7", "#666666")

save_fig <- function(id, caption, draw, w = 7.2, h = 4.2) {
  png(file.path(FIG, paste0(id, ".png")), width = w, height = h,
      units = "in", res = 300); draw(); dev.off()
  pdf(file.path(FIG, paste0(id, ".pdf")), width = w, height = h,
      timestamp = FALSE, producer = FALSE); draw(); dev.off()
  writeLines(caption, file.path(FIG, paste0(id, ".md")))
  cat(sprintf("  %-22s png + pdf + caption\n", id))
}

save_figure_data <- function(obj, id) {
  saveRDS(obj, file.path(paths$tables, paste0(id, ".rds")))
  write.csv(obj, file.path(paths$tables, "supplement", paste0(id, ".csv")),
            row.names = FALSE, na = "")
}

irf <- function(theta, beta, lambda) plogis(lambda * (theta - beta))

## ---- F-irf : item response functions and item information ---------------
draw_irf <- function() {
  th <- seq(-4, 4, length.out = 401)
  op <- par(mfrow = c(1, 2), mar = c(4.2, 4.2, 2.4, 0.8), cex.axis = .9)
  spec <- list(c(0, 1), c(-1, 1), c(0, 2), c(0, 0.5))
  labs <- c(expression(beta==0*","~lambda==1), expression(beta==-1*","~lambda==1),
            expression(beta==0*","~lambda==2), expression(beta==0*","~lambda==0.5))
  plot(NA, xlim = c(-4, 4), ylim = c(0, 1), xlab = expression(theta),
       ylab = "P(correct)", main = "Item response function")
  abline(h = 0.5, col = "grey85"); abline(v = 0, col = "grey85")
  for (k in seq_along(spec))
    lines(th, irf(th, spec[[k]][1], spec[[k]][2]), col = PAL[k], lwd = 2.2)
  legend("bottomright", legend = labs, col = PAL[1:4], lwd = 2.2, bty = "n", cex = .85)

  plot(NA, xlim = c(-4, 4), ylim = c(0, 1.05), xlab = expression(theta),
       ylab = "item information", main = "Item information")
  abline(v = 0, col = "grey85")
  for (k in seq_along(spec)) {
    p <- irf(th, spec[[k]][1], spec[[k]][2])
    lines(th, spec[[k]][2]^2 * p * (1 - p), col = PAL[k], lwd = 2.2)
  }
  par(op)
}
save_fig("F-irf", paste(
  "Item response functions (left) and item information (right) for four items under",
  "the 2PL. Difficulty $\\beta$ shifts the curve horizontally; discrimination",
  "$\\lambda$ sets its slope at $\\theta=\\beta$, which is $\\lambda/4$. The Rasch model",
  "is $\\lambda\\equiv1$ (blue). Item information $\\lambda_i^2\\pi_{pi}(1-\\pi_{pi})$ peaks",
  "at $\\theta=\\beta_i$ with height $\\lambda_i^2/4$: a high-discrimination item separates",
  "sharply near its difficulty and says little elsewhere, a low-discrimination item is",
  "mildly informative over a wide range. Generated by code/R/09-figures.R."),
  draw_irf)

## ---- F-shrinkage-weight : w_p against error variance --------------------
draw_wt <- function() {
  se2 <- seq(0.01, 4, length.out = 400)
  op <- par(mar = c(4.2, 4.4, 2.4, 0.8), cex.axis = .9)
  plot(NA, xlim = c(0, 4), ylim = c(0, 1), xlab = expression(se(hat(theta)[p])^2),
       ylab = expression(w[p]), main = "Shrinkage weight")
  for (k in seq_along(s <- c(0.25, 0.5, 1, 2)))
    lines(se2, s[k] / (s[k] + se2), col = PAL[k], lwd = 2.2)
  abline(h = c(.5, .8), col = "grey88", lty = 3)
  legend("topright", legend = sapply(s, function(z)
    as.expression(bquote(sigma[theta]^2 == .(z)))),
    col = PAL[1:4], lwd = 2.2, bty = "n", cex = .85)
  par(op)
}
save_fig("F-shrinkage-weight", paste(
  "The shrinkage weight $w_p=\\sigma^2_\\theta/(\\sigma^2_\\theta+se(\\hat\\theta_p)^2)$",
  "against the conditional error variance, at four values of the between-person",
  "variance. The weight is the fraction of a person's estimate that comes from their own",
  "responses rather than from the population. It falls with measurement error and rises",
  "with between-person spread, which is why reliability is a property of a test *in a",
  "population* and not of a test. Generated by code/R/09-figures.R."),
  draw_wt, w = 5.6, h = 4.2)

## ---- F-ensemble-shrink : three histograms, and what the standard repair does ----
ensemble_shrink_data <- local({
  set.seed(11)
  P <- 4000; s2 <- 1; se2 <- 0.6
  th <- rnorm(P, 0, sqrt(s2)); hat <- th + rnorm(P, 0, sqrt(se2))
  w <- s2 / (s2 + se2); eap <- w * hat
  set.seed(181)
  Q <- 20000; sev <- 0.55
  tb <- ifelse(runif(Q) < .5, rnorm(Q, -1, .35), rnorm(Q, 1, .35))
  tb <- (tb - mean(tb)) / sd(tb)
  hb <- tb + rnorm(Q, 0, sqrt(sev))
  s2b <- var(tb); wb <- s2b / (s2b + sev)
  eb <- wb * hb; post_var <- wb * sev
  ab <- sqrt(1 + (1 - 1/Q) * mean(post_var) / mean((eb - mean(eb))^2))
  cb <- mean(eb) + (eb - mean(eb)) * ab
  list(P = P, s2 = s2, se2 = se2, th = th, hat = hat, w = w, eap = eap,
       Q = Q, sev = sev, tb = tb, hb = hb, wb = wb, eb = eb, cb = cb)
})
excess_kurtosis <- function(x) mean((x - mean(x))^4) / sd(x)^4 - 3
empirical_ks <- function(x, truth) {
  at <- sort(unique(c(x, truth)))
  max(abs(ecdf(x)(at) - ecdf(truth)(at)))
}
ensemble_shrink_summary <- with(ensemble_shrink_data, data.frame(
  metric = c("latent_variance", "error_variance_left", "shrinkage_weight_left",
             "error_variance_bimodal", "true_sd", "posterior_mean_sd", "cb_sd",
             "true_excess_kurtosis", "posterior_mean_excess_kurtosis",
             "cb_excess_kurtosis", "ks_ml", "ks_posterior_mean", "ks_cb"),
  value = c(s2, se2, w, sev, sd(tb), sd(eb), sd(cb), excess_kurtosis(tb),
            excess_kurtosis(eb), excess_kurtosis(cb), empirical_ks(hb, tb),
            empirical_ks(eb, tb), empirical_ks(cb, tb)),
  stringsAsFactors = FALSE))
save_figure_data(ensemble_shrink_summary, "F-ensemble-shrink-summary")

draw_ens <- function() {
  e <- ensemble_shrink_data
  with(e, {
  op <- par(mfrow = c(1, 2), mar = c(4.2, 4.2, 2.4, 0.8), cex.axis = .9, cex.main = .98)
  d0 <- density(th); d1 <- density(hat); d2 <- density(eap)
  plot(NA, xlim = c(-4, 4), ylim = c(0, max(d0$y, d1$y, d2$y) * 1.06),
       xlab = expression(theta), ylab = "density",
       main = "One truth, two wrong histograms")
  lines(d0, col = PAL[5], lwd = 3); lines(d1, col = PAL[2], lwd = 2.2)
  lines(d2, col = PAL[1], lwd = 2.2)
  legend("topright", bty = "n", cex = .8, lwd = c(3, 2.2, 2.2),
         col = c(PAL[5], PAL[2], PAL[1]),
         legend = c(sprintf("true G  (SD %.2f)", sd(th)),
                    sprintf("ML estimates  (SD %.2f)", sd(hat)),
                    sprintf("posterior means  (SD %.2f)", sd(eap))))

  ## right panel: the same machinery under a BIMODAL truth, with constrained Bayes
  e0 <- density(tb); e1 <- density(eb); e2 <- density(cb)
  plot(NA, xlim = c(-3, 3), ylim = c(0, max(e0$y, e1$y, e2$y) * 1.06),
       xlab = expression(theta), ylab = "density",
       main = "What constrained Bayes fixes, and does not")
  lines(e0, col = PAL[5], lwd = 3); lines(e1, col = PAL[1], lwd = 2.2, lty = 2)
  lines(e2, col = PAL[3], lwd = 2.4)
  legend("topright", bty = "n", cex = .78, lwd = c(3, 2.2, 2.4), lty = c(1, 2, 1),
         col = c(PAL[5], PAL[1], PAL[3]),
         legend = c(sprintf("true G  (SD %.2f, ex. kurt %.2f)", sd(tb),
                            excess_kurtosis(tb)),
                    sprintf("posterior means  (SD %.2f)", sd(eb)),
                    sprintf("constrained Bayes  (SD %.2f, ex. kurt %.2f)", sd(cb),
                            excess_kurtosis(cb))))
  par(op)
  })
}
save_fig("F-ensemble-shrink", paste(
  "**Left:** why neither obvious histogram estimates the distribution of the latent",
  "traits. Simulated with unit latent variance and a fixed constant error variance. The",
  "within-person estimates carry measurement noise on top of the true",
  "variation and are too spread out; the posterior means are shrunk and too concentrated.",
  "A cut-score applied to either misstates the proportion below it, in opposite",
  "directions. **Right:** the same machinery under a sharply bimodal truth, with the",
  "constrained-Bayes repair of @sec-ch18. CB restores the standard deviation almost",
  "exactly. It does not restore the shape, and cannot: @prp-cb-affine shows CB is a",
  "positive affine map of the posterior means, so every standardized moment above the",
  "second is inherited unchanged — the excess kurtosis stays at the posterior means'",
  "value while the truth's is far lower. Bimodality is a shape feature and an affine map",
  "has no access to it. Seeds fixed; numerical moments and KS distances are frozen in",
  "tables/F-ensemble-shrink-summary.rds with a CSV mirror; illustrative, no inference rests on it.",
  "Generated by code/R/09-figures.R."),
  draw_ens, w = 8.0, h = 4.2)

cat("figures written to", FIG, "\n")

## ---- F-tif-msem : test information, local SEM, and where MSEM comes from ----
draw_tif <- function() {
  th <- seq(-4, 4, length.out = 401)
  set.seed(7)                       # fixed: illustrative, not inferential
  beta <- seq(-1.6, 1.6, length.out = 20)     # 20 items, moderately targeted
  info <- function(t) sum(plogis(t - beta) * (1 - plogis(t - beta)))
  J  <- vapply(th, info, numeric(1))
  se <- 1 / sqrt(J)
  op <- par(mfrow = c(1, 2), mar = c(4.2, 4.3, 2.4, 0.8), cex.axis = .9)

  plot(th, J, type = "l", lwd = 2.4, col = PAL[1], xlab = expression(theta),
       ylab = expression(J(theta)), main = "Test information")
  rug(beta, col = PAL[5]); abline(v = range(beta), col = "grey88", lty = 3)

  plot(th, se, type = "l", lwd = 2.4, col = PAL[2], ylim = c(0, 1.6),
       xlab = expression(theta), ylab = expression(se(hat(theta))),
       main = "Local standard error")
  abline(v = range(beta), col = "grey88", lty = 3)
  ## MSEM under a standard normal G, and its root
  w  <- dnorm(th); w <- w / sum(w)
  msem <- sum(w * se^2); rmsem <- sqrt(msem)
  mean_se <- sum(w * se)
  abline(h = rmsem,   col = PAL[3], lwd = 2, lty = 2)
  abline(h = mean_se, col = PAL[4], lwd = 2, lty = 4)
  legend("top", bty = "n", cex = .8, lwd = c(2, 2), lty = c(2, 4),
         col = c(PAL[3], PAL[4]),
         legend = c(sprintf("RMSEM = %.3f", rmsem),
                    sprintf("mean se = %.3f", mean_se)))
  par(op)
}
save_fig("F-tif-msem", paste(
  "Test information (left) and the local standard error it implies (right), for a",
  "20-item Rasch test with difficulties evenly spaced on $[-1.6, 1.6]$ (tick marks).",
  "Information is additive over items and peaks where the items sit; the standard error",
  "is the reciprocal square root and rises steeply outside the range the items cover.",
  "The two horizontal lines average the right-hand curve against a standard normal $G$:",
  "RMSEM averages on the variance scale and then takes a root, the mean standard error",
  "averages on the standard-error scale, and the first exceeds the second by",
  "@prp-msem-jensen. Seed fixed; illustrative, no inference rests on it.",
  "Generated by code/R/09-figures.R."),
  draw_tif)

## ---- F-jensen : the three marginal functionals, and how far apart they are ----
## Deterministic quadrature; no simulation, no seed.
draw_jensen <- function() {
  Jf <- function(b) function(t)
    vapply(t, function(z) sum(plogis(z - b) * (1 - plogis(z - b))), numeric(1))
  gdens <- list(
    normal  = function(t) dnorm(t),
    heavy   = function(t) dt(t / sqrt(3), df = 3),
    skew    = function(t) 0.75 * dnorm(t, -0.6, 0.5) + 0.25 * dnorm(t, 1.8, 0.9),
    bimodal = function(t) 0.5 * dnorm(t, -1.2, 0.5) + 0.5 * dnorm(t, 1.2, 0.5))
  ## every G is standardized to mean 0, variance 1 before use, so the three
  ## functionals are compared on the same latent-variance basis.
  trio <- function(I, gfun) {
    b  <- seq(-1.6, 1.6, length.out = I)
    t  <- seq(-12, 12, length.out = 6001)
    w  <- gfun(t); w <- w / sum(w)
    mu <- sum(w * t); s <- sqrt(sum(w * (t - mu)^2))
    tz <- (t - mu) / s; k <- abs(tz) < 8
    tz <- tz[k]; w <- w[k] / sum(w[k])
    J  <- Jf(b)(tz)
    c(wbar = 1 / (1 + sum(w / J)),
      rTh  = sum(w * J / (J + 1)),
      rTil = sum(w * J) / (sum(w * J) + 1))
  }
  Igrid <- c(5, 8, 12, 18, 25, 35, 50, 70, 95)
  op <- par(mfrow = c(1, 2), mar = c(4.2, 4.4, 2.4, 0.8), cex.axis = .9)

  z <- t(vapply(Igrid, trio, numeric(3), gfun = gdens$normal))
  plot(NA, xlim = c(0.35, 0.98), ylim = c(0, 0.010), xlab = expression(bar(w)),
       ylab = "distance above w-bar", main = "The sandwich, normal G")
  polygon(c(z[, "wbar"], rev(z[, "wbar"])),
          c(z[, "rTil"] - z[, "wbar"], rev(z[, "rTh"] - z[, "wbar"])),
          col = "#D55E0022", border = NA)
  polygon(c(z[, "wbar"], rev(z[, "wbar"])),
          c(z[, "rTh"] - z[, "wbar"], rep(0, nrow(z))),
          col = "#009E7322", border = NA)
  lines(z[, "wbar"], z[, "rTil"] - z[, "wbar"], col = PAL[2], lwd = 2.4)
  lines(z[, "wbar"], z[, "rTh"]  - z[, "wbar"], col = PAL[3], lwd = 2.4, lty = 2)
  abline(h = 0, col = PAL[5], lwd = 2)
  legend("topright", bty = "n", cex = .8, lwd = c(2.4, 2.4, 2), lty = c(1, 2, 1),
         col = c(PAL[2], PAL[3], PAL[5]),
         legend = c(expression(tilde(rho)), expression(rho[Theta]), expression(bar(w))))

  plot(NA, xlim = c(0.35, 0.98), ylim = c(0, 0.032), xlab = expression(bar(w)),
       ylab = expression(tilde(rho) - bar(w)), main = "Outer gap, by shape of G")
  for (k in seq_along(gdens)) {
    zz <- t(vapply(Igrid, trio, numeric(3), gfun = gdens[[k]]))
    lines(zz[, "wbar"], zz[, "rTil"] - zz[, "wbar"], col = PAL[k], lwd = 2.4)
  }
  legend("topright", bty = "n", cex = .8, lwd = 2.4, col = PAL[seq_along(gdens)],
         legend = c("normal", "heavy-tailed (t3)", "skewed", "bimodal"))
  par(op)
}
save_fig("F-jensen", paste(
  "The three marginal reliability functionals of @sec-ch08-functionals, over Rasch tests",
  "of 5 to 95 items with difficulties evenly spaced on $[-1.6,1.6]$. Left: the two",
  "functionals plotted as distances above $\\bar w$, so the sandwich is visible;",
  "$\\rho_\\Theta$ lies strictly between the other two everywhere, and the inner gap is",
  "roughly half the outer one. Note the vertical scale. Right: the outer gap",
  "$\\tilde\\rho-\\bar w$ under four latent distributions, each standardized to variance 1.",
  "Heavy tails widen the gap and bimodality narrows it relative to the normal, because",
  "the gap tracks how much information varies over the mass of $G$, not how far $G$ is",
  "from normal. Every gap here is below 0.03. Deterministic quadrature; no simulation.",
  "Generated by code/R/09-figures.R."),
  draw_jensen)

## ---- F-rel-items : the inverse design problem, and the difficulty-spread lever ----
## Population forward map w-bar(I, beta) = 1/(1 + E_G[J(theta)^-1]) under theta ~ N(0,1)
## with item parameters KNOWN. This is the asymptotic analogue of the manuscript's
## Monte Carlo search, not a re-run of it; the offset between the two is the subject
## of ch. 9 sec. 4. Each replicate draws one ordered 400-item bank. Every candidate
## length uses a prefix of that same bank, so the objective cannot change mid-search.
q_rel <- seq(-5, 5, length.out = 401)
gw_rel <- dnorm(q_rel); gw_rel <- gw_rel / sum(gw_rel)
tg_rel <- seq(0.45, 0.92, by = 0.01)
sds_rel <- c(0.5, 1.0, 1.5)
R_rel <- 120L
rel_curve <- function(bank) {
  pp <- plogis(outer(q_rel, bank, "-"))
  jcum <- t(apply(pp * (1 - pp), 1L, cumsum))
  1 / (1 + colSums(gw_rel / jcum))
}
set.seed(20260804)
rel_draws <- lapply(sds_rel, function(s) {
  z <- replicate(R_rel, {
    curve <- rel_curve(rnorm(400L, 0, s))
    vapply(tg_rel, function(target) {
      hit <- which(curve >= target)
      if (length(hit)) hit[1L] else NA_integer_
    }, integer(1))
  })
  rowMeans(z)
})
rel_summary <- data.frame(
  target = rep(tg_rel, times = length(sds_rel)),
  sd_beta = rep(sds_rel, each = length(tg_rel)),
  mean_items = unlist(rel_draws),
  replicates = R_rel,
  max_bank = 400L,
  seed = 20260804L
)
saveRDS(rel_summary, file.path(paths$tables, "F-rel-items-summary.rds"))
write.csv(rel_summary, file.path(paths$tables, "supplement", "F-rel-items-summary.csv"),
          row.names = FALSE)

draw_rel_items <- function() {
  Z <- vapply(sds_rel, function(s)
    rel_summary$mean_items[rel_summary$sd_beta == s], numeric(length(tg_rel)))

  op <- par(mar = c(4.2, 4.4, 2.4, 0.8), cex.axis = .9)
  plot(NA, xlim = c(0.45, 0.95), ylim = c(0, 75), xlab = expression(bar(w)),
       ylab = "items required", main = "The inverse design problem")
  for (k in seq_along(sds_rel)) lines(tg_rel, Z[, k], col = PAL[k], lwd = 2.4)
  ## the manuscript's Table 2, read from the printed table
  tab_w <- c(0.5, 0.6, 0.7, 0.8, 0.9); tab_I <- c(10.1, 14.3, 22.8, 31.4, 60.7)
  points(tab_w, tab_I, pch = 21, bg = PAL[4], col = "white", cex = 1.5, lwd = 1.5)
  legend("topleft", bty = "n", cex = .82,
         lwd = c(2.4, 2.4, 2.4, NA), lty = c(1, 1, 1, NA),
         pch = c(NA, NA, NA, 21), pt.bg = c(NA, NA, NA, PAL[4]), pt.cex = 1.4,
         col = c(PAL[1], PAL[2], PAL[3], "black"),
         legend = c(expression(SD(beta) == 0.5), expression(SD(beta) == 1.0),
                    expression(SD(beta) == 1.5), "manuscript Table 2"))
  par(op)
}
save_fig("F-rel-items", paste(
  "Items required to reach a target reliability, under the population forward map",
  "$\\bar w = 1/(1+\\operatorname{E}_G[\\mathcal{J}^{-1}])$ with $\\theta\\sim N(0,1)$ and item",
  "parameters known, averaged over 120 fixed-prefix item-bank draws at each target. The",
  "curve is convex: the last tenth of reliability costs more items than the first four",
  "combined. Narrower item-difficulty distributions require fewer items at every target,",
  "which is the lever @sec-ch09-levers names third. The manuscript's Table 2 lies above",
  "the matching $SD(\\beta)=1$ curve at every target. The gap is descriptive: the figure",
  "uses a population functional with known item parameters, whereas the manuscript uses",
  "its realized calibration procedure, so these curves do not identify the cause.",
  "Seed fixed; illustrative, no inference rests on it.",
  "Generated by code/R/09-figures.R."),
  draw_rel_items, w = 6.2, h = 4.4)

## ---- F-stein : the James-Stein risk, and where the gain actually is ----
## Risk from James & Stein (1961, sec. 2): rho = p - (p-2)^2 E_K[1/(p-2+2K)],
## K ~ Poisson(||xi||^2 / 2). Verified against the two values they state:
## rho = 2 at xi = 0 and rho -> p as ||xi||^2 -> infinity. Deterministic.
draw_stein <- function() {
  js_risk <- function(p, s2) {                     # s2 = ||xi||^2
    lam <- s2 / 2
    k <- 0:max(200L, ceiling(lam + 12 * sqrt(lam + 1)))
    p - (p - 2)^2 * sum(dpois(k, lam) / (p - 2 + 2 * k))
  }
  ps <- c(3, 10, 200)
  op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.4, 0.8), cex.axis = .9)

  s2 <- seq(0, 60, length.out = 121)
  plot(NA, xlim = c(0, 60), ylim = c(0, 1.05), xlab = expression("||"*xi*"||"^2),
       ylab = "risk / p", main = "James-Stein risk, relative to p")
  abline(h = 1, col = PAL[5], lwd = 2)
  for (k in seq_along(ps)) {
    r <- vapply(s2, js_risk, numeric(1), p = ps[k])
    lines(s2, r / ps[k], col = PAL[k], lwd = 2.4)
  }
  legend("bottomright", bty = "n", cex = .82,
         lwd = c(2.4, 2.4, 2.4, 2), col = c(PAL[1:3], PAL[5]),
         legend = c("p = 3", "p = 10", "p = 200", "usual estimator"))

  ## per-coordinate spread is what matters: ||xi||^2 = p * (mean squared coordinate)
  m2 <- seq(0, 3, length.out = 121)
  plot(NA, xlim = c(0, 3), ylim = c(0, 1.05), xlab = expression("||"*xi*"||"^2/p),
       ylab = "risk / p", main = "Against spread per coordinate")
  abline(h = 1, col = PAL[5], lwd = 2)
  for (k in seq_along(ps)) {
    r <- vapply(m2 * ps[k], js_risk, numeric(1), p = ps[k])
    lines(m2, r / ps[k], col = PAL[k], lwd = 2.4)
  }
  abline(v = 1, col = "grey85", lty = 3)
  par(op)
}
save_fig("F-stein", paste(
  "The risk of the James--Stein estimator @eq-james-stein relative to the risk $p$ of the",
  "usual estimator, computed from the expression James and Stein give in their § 2.",
  "Left: against $\\|\\xi\\|^2$. The curve starts at $2/p$ — a hundredfold improvement at",
  "$p=200$ — and climbs toward 1, and the larger $p$ is the more slowly it climbs.",
  "Right: the same curves against $\\|\\xi\\|^2/p$, the mean squared coordinate, which is",
  "the quantity that is comparable across dimensions; the dotted line marks a unit",
  "population variance. Read at $\\|\\xi\\|^2/p = 1$ the gain is modest for $p=3$ and",
  "still substantial for $p=200$. Dimension determines the inadmissibility threshold,",
  "while both dimension and signal magnitude determine the size of the gain.",
  "Deterministic; no simulation. Generated by code/R/09-figures.R."),
  draw_stein)

## ---- F-nonnormal-shapes : the sum-score fallacy, in both directions ----
## Exact computation throughout. P(X = k | theta) by the Poisson-binomial
## recursion; P(X = k) by quadrature over G. No simulation, no seed.
draw_nonnormal <- function() {
  pbin <- function(p) { d <- 1; for (pi in p) d <- c(d * (1 - pi), 0) + c(0, d * pi); d }
  ss <- function(beta, tq, wq) {
    o <- numeric(length(beta) + 1L)
    for (j in seq_along(tq)) o <- o + wq[j] * pbin(plogis(tq[j] - beta))
    o / sum(o)
  }
  std <- function(dens, n = 4001) {            # standardize G to mean 0, variance 1
    t <- seq(-12, 12, length.out = n); w <- dens(t); w <- w / sum(w)
    mu <- sum(w * t); s <- sqrt(sum(w * (t - mu)^2))
    list(t = (t - mu) / s, w = w, d = w / (diff(t)[1] / s))
  }
  Gn <- std(function(t) dnorm(t))
  Gb <- std(function(t) 0.5 * dnorm(t, -1, 0.30) + 0.5 * dnorm(t, 1, 0.30))

  op <- par(mfrow = c(2, 2), mar = c(4.0, 4.2, 2.6, 0.8), cex.axis = .9, cex.main = 1)

  ## row 1: normal G, skewed score distribution
  plot(Gn$t, Gn$d, type = "l", lwd = 2.4, col = PAL[1], xlim = c(-3.5, 3.5),
       xlab = expression(theta), ylab = "density", main = "G is exactly normal")
  b1 <- rep(-1.5, 5); d1 <- ss(b1, Gn$t, Gn$w)
  barplot(d1, names.arg = 0:5, col = PAL[2], border = "white", ylim = c(0, 0.42),
          xlab = "sum score", ylab = "probability",
          main = "5 easy items: score skew -0.99")

  ## row 2: bimodal G, bell-shaped score distribution
  plot(Gb$t, Gb$d, type = "l", lwd = 2.4, col = PAL[1], xlim = c(-3.5, 3.5),
       xlab = expression(theta), ylab = "density", main = "G is sharply bimodal")
  lines(Gn$t, Gn$d, col = "grey75", lwd = 1.6, lty = 2)
  b2 <- seq(-2.5, 2.5, length.out = 6)
  d2 <- ss(b2, Gb$t, Gb$w); d2n <- ss(b2, Gn$t, Gn$w)
  bp <- barplot(d2, names.arg = 0:6, col = PAL[3], border = "white", ylim = c(0, 0.34),
                xlab = "sum score", ylab = "probability",
                main = "6 spread items: TV from normal G = 0.035")
  points(bp, d2n, pch = 18, cex = 1.5, col = PAL[5])
  legend("topright", bty = "n", cex = .8, pch = c(15, 18), col = c(PAL[3], PAL[5]),
         legend = c("under bimodal G", "under normal G"))
  par(op)
}
save_fig("F-nonnormal-shapes", paste(
  "The sum-score fallacy, computed exactly. **Top:** a standard normal latent",
  "distribution, and the sum-score distribution it produces on five items of difficulty",
  "$-1.5$ — skewness $-0.99$ with $38\\%$ of respondents at the ceiling. A markedly",
  "non-normal score distribution from an exactly normal $G$. **Bottom:** a sharply",
  "bimodal $G$ (standard normal dashed for reference), and the sum-score distribution it",
  "produces on six items spread over $[-2.5, 2.5]$ — symmetric, single-peaked, and almost",
  "indistinguishable from what the normal $G$ gives on the same test (diamonds); the two",
  "differ by $0.035$ in total variation. Sum-score probabilities are exact:",
  "$\\Pr(X=k\\mid\\theta)$ by the Poisson-binomial recursion, integrated over $G$ by",
  "quadrature. No simulation. Generated by code/R/09-figures.R."),
  draw_nonnormal, w = 7.6, h = 6.4)

## ---- F-flexible-g : representational capacity, not estimation performance ----
## Each family's best approximation to one target density, by minimizing KL on a
## fixed grid. This says what a family CAN represent given unlimited data; it says
## nothing about how well any of them is estimated. Deterministic (fixed starts).
draw_flexg <- function() {
  x  <- seq(-4, 4, length.out = 1201); dx <- x[2] - x[1]
  ## target: skewed AND bimodal, standardized to mean 0 variance 1
  raw <- 0.62 * dnorm(x, -0.7, 0.45) + 0.38 * dnorm(x, 1.15, 0.75)
  w0  <- raw / sum(raw); mu <- sum(w0 * x); sd0 <- sqrt(sum(w0 * (x - mu)^2))
  tgt <- approxfun((x - mu) / sd0, raw * sd0, rule = 2)(x)
  tgt <- tgt / (sum(tgt) * dx)

  kl <- function(q) { q <- pmax(q, 1e-12); q <- q / (sum(q) * dx)
                      sum(tgt * log(pmax(tgt, 1e-12) / q)) * dx }
  ## normal: KL is minimized by moment matching
  fit_n <- dnorm(x, 0, 1)
  ## skew-normal, parameterized by (xi, omega, alpha)
  dsn <- function(p) 2 / p[2] * dnorm((x - p[1]) / p[2]) * pnorm(p[3] * (x - p[1]) / p[2])
  fit_s <- dsn(optim(c(-0.5, 1.2, 2), function(p)
    if (p[2] <= 0.05) 1e6 else kl(dsn(p)), control = list(maxit = 3000))$par)
  ## K-component normal mixture with equal-ish weights estimated on the logit scale
  mix <- function(p, K) {
    w <- exp(c(0, p[1:(K - 1)])); w <- w / sum(w)
    m <- p[K:(2 * K - 1)]; s <- exp(p[(2 * K):(3 * K - 1)])
    rowSums(vapply(seq_len(K), function(k) w[k] * dnorm(x, m[k], s[k]), numeric(length(x))))
  }
  fit_mix <- function(K, start) mix(optim(start, function(p) kl(mix(p, K)),
                                          control = list(maxit = 8000))$par, K)
  fit_2 <- fit_mix(2, c(0, -0.7, 0.9, log(0.5), log(0.7)))
  fit_5 <- fit_mix(5, c(rep(0, 4), seq(-1.6, 1.6, length.out = 5), rep(log(0.45), 5)))

  op <- par(mar = c(4.2, 4.3, 2.4, 0.8), cex.axis = .9)
  plot(x, tgt, type = "l", lwd = 3.2, col = PAL[5], xlim = c(-3, 3),
       ylim = c(0, max(tgt) * 1.12), xlab = expression(theta), ylab = "density",
       main = "Best approximation to one target, by family")
  lines(x, fit_n, col = PAL[1], lwd = 2.2, lty = 2)
  lines(x, fit_s, col = PAL[2], lwd = 2.2)
  lines(x, fit_2, col = PAL[3], lwd = 2.2)
  lines(x, fit_5, col = PAL[4], lwd = 2.2, lty = 3)
  legend("topright", bty = "n", cex = .82, lwd = c(3.2, 2.2, 2.2, 2.2, 2.2),
         lty = c(1, 2, 1, 1, 3), col = c(PAL[5], PAL[1], PAL[2], PAL[3], PAL[4]),
         legend = c("target G",
                    sprintf("normal (KL %.3f)", kl(fit_n)),
                    sprintf("skew-normal (KL %.3f)", kl(fit_s)),
                    sprintf("2-component mixture (KL %.3f)", kl(fit_2)),
                    sprintf("5-component mixture (KL %.3f)", kl(fit_5))))
  par(op)
}
save_fig("F-flexible-g", paste(
  "What each family of latent-trait distributions **can represent**, shown as its best",
  "approximation to one skewed and bimodal target, obtained by minimizing",
  "Kullback--Leibler divergence on a fixed grid. The normal can match only location and",
  "scale. The skew-normal captures the asymmetry and cannot produce a second mode at all.",
  "The two-component mixture recovers the target exactly, but only because the target",
  "*is* a two-component normal mixture — the fit is circular and is shown to make the",
  "point that follows. Five components do no better than two because a nonminimal",
  "representation can duplicate or zero out components. This does not refute",
  "identification of the minimal order under standard conditions. @sec-ch14-mixtures",
  "contrasts a fixed order, an MFM prior on population order, and a DPM prior on occupied",
  "partitions.",
  "This figure is about representational capacity given unlimited data. It says nothing",
  "about how well any family is *estimated* from a finite sample, which is where the",
  "families differ most and which @tbl-flexible-g reports separately.",
  "Deterministic; fixed optimizer starts. Generated by code/R/09-figures.R."),
  draw_flexg, w = 6.6, h = 4.4)

## ---- F-stick-crp : stick-breaking weights, and what they imply ----
## Left: sorted stick weights at three concentrations. Right: the prior on the
## LARGEST weight, at concentrations matched to E[K_200] = 3, 5, 10. The right
## panel is the "unintended prior" of ch. 15 sec. 8, quantified. Values printed
## in the figure and chapter are computed once and frozen as RDS/CSV artifacts.
match_alpha <- function(target, J)
  uniroot(function(a) a * (digamma(a + J) - digamma(a)) - target, c(1e-4, 500))$root
set.seed(12)
stick_targets <- c(3, 5, 10)
stick_R <- 6000L
stick_N <- 1500L
stick_draws <- lapply(stick_targets, function(target) {
  a <- match_alpha(target, 200)
  replicate(stick_R, {
    v <- rbeta(stick_N, 1, a)
    max(v * cumprod(c(1, 1 - v[-stick_N])))
  })
})
stick_summary <- data.frame(
  target_clusters = stick_targets,
  alpha = vapply(stick_targets, match_alpha, numeric(1), J = 200),
  median_largest = vapply(stick_draws, median, numeric(1)),
  prob_largest_gt_half = vapply(stick_draws, function(x) mean(x > 0.5), numeric(1)),
  replicates = stick_R,
  truncation = stick_N,
  seed = 12L
)
saveRDS(stick_summary, file.path(paths$tables, "F-stick-crp-summary.rds"))
write.csv(stick_summary, file.path(paths$tables, "supplement", "F-stick-crp-summary.csv"),
          row.names = FALSE)

draw_stick <- function() {
  op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.6, 0.8), cex.axis = .9)

  set.seed(11)                       # fixed: illustrative, not inferential
  alphas <- c(0.5, 2, 10)
  plot(NA, xlim = c(1, 25), ylim = c(0, 0.85), xlab = "component (sorted)",
       ylab = "weight", main = "Stick-breaking weights")
  for (k in seq_along(alphas)) {
    v <- rbeta(500, 1, alphas[k]); p <- sort(v * cumprod(c(1, 1 - v[-500])), decreasing = TRUE)
    lines(1:25, p[1:25], type = "b", pch = 16, cex = .7, col = PAL[k], lwd = 2)
  }
  legend("topright", bty = "n", cex = .85, lwd = 2, pch = 16, col = PAL[1:3],
         legend = sapply(alphas, function(a) as.expression(bquote(alpha == .(a)))))

  plot(NA, xlim = c(0, 1), ylim = c(0, 4.6), xlab = "largest stick weight",
       ylab = "prior density", main = expression("Induced prior, matched on E["*K[200]*"]"))
  for (k in seq_along(stick_targets))
    lines(density(stick_draws[[k]], from = 0, to = 1), col = PAL[k], lwd = 2.4)
  abline(v = 0.5, col = "grey80", lty = 3)
  legend("topleft", bty = "n", cex = .8, lwd = 2.4, col = PAL[1:3],
         legend = sprintf("E[K] = %d  (median %.2f)", stick_targets,
                          stick_summary$median_largest))
  par(op)
}
stick5 <- stick_summary[stick_summary$target_clusters == 5, ]
save_fig("F-stick-crp", paste(
  "**Left:** stick-breaking weights $p_n = \\theta_n\\prod_{m<n}(1-\\theta_m)$ with",
  "$\\theta_m \\sim \\mathrm{Beta}(1,\\alpha)$, sorted, at three concentrations. Small",
  "$\\alpha$ concentrates the population into few components; large $\\alpha$ spreads it.",
  "**Right:** the prior this induces on the *largest* weight, at concentrations chosen so",
  "that $\\operatorname{E}[K_{200}]$ equals 3, 5 and 10 — the quantity an analyst usually",
  sprintf("elicits. Matching $\\operatorname{E}[K_{200}] = 5$ requires $\\alpha = %.2f$, under which the", stick5$alpha),
  sprintf("largest component holds a median $%.0f\\%%$ of the population and exceeds half of it with", 100 * stick5$median_largest),
  sprintf("prior probability $%.2f$. Eliciting a cluster count is therefore also, silently, an", stick5$prob_largest_gt_half),
  "assertion about dominance. Seed fixed; illustrative.",
  "Generated by code/R/09-figures.R."),
  draw_stick, w = 7.4, h = 4.2)

## ---- F-k-alpha : Antoniak's distribution of the number of clusters ----
## Exact PMF from unsigned Stirling numbers of the first kind, on the log scale.
draw_kalpha <- function() {
  log_s1 <- function(n) {
    lg <- 0
    if (n == 1) return(lg)
    for (m in 2:n) {
      prev <- lg; new <- rep(-Inf, m)
      for (k in 1:m) {
        a <- if (k >= 2) prev[k - 1] else -Inf
        b <- if (k <= m - 1) prev[k] + log(m - 1) else -Inf
        new[k] <- if (is.infinite(a) && is.infinite(b)) -Inf else
          max(a, b) + log1p(exp(-abs(a - b)))
      }
      lg <- new
    }
    lg
  }
  pmf <- function(n, alpha) exp(log_s1(n) + (1:n) * log(alpha) -
                                  (lgamma(alpha + n) - lgamma(alpha)))
  op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.6, 0.8), cex.axis = .9)

  alphas <- c(0.5, 1, 5)
  plot(NA, xlim = c(0, 30), ylim = c(0, 0.42), xlab = expression(K[200]),
       ylab = "prior probability", main = expression("Antoniak's law for "*K[J]*", J = 200"))
  for (k in seq_along(alphas)) {
    p <- pmf(200, alphas[k])
    lines(1:30, p[1:30], type = "h", lwd = 3, col = adjustcolor(PAL[k], 0.75))
  }
  legend("topright", bty = "n", cex = .85, lwd = 3, col = PAL[1:3],
         legend = sapply(alphas, function(a) as.expression(bquote(alpha == .(a)))))

  J <- 10^seq(1, 5, length.out = 60)
  plot(NA, xlim = range(J), ylim = c(0, 62), log = "x", xlab = "J (log scale)",
       ylab = expression(E*"["*K[J]*"]"), main = "Logarithmic growth")
  for (k in seq_along(alphas))
    lines(J, alphas[k] * (digamma(alphas[k] + J) - digamma(alphas[k])),
          col = PAL[k], lwd = 2.4)
  par(op)
}
save_fig("F-k-alpha", paste(
  "Antoniak's distribution of the number of occupied clusters. **Left:** the exact prior",
  "pmf of $K_J$ at $J = 200$, computed from unsigned Stirling numbers of the first kind,",
  "for three concentrations. The distribution is tight — at $\\alpha = 1$ almost all the",
  "mass lies between 2 and 10, a central 95\\% interval — so $\\alpha$ is a strong",
  "statement, not a vague one. **Right:** $\\operatorname{E}[K_J] = \\alpha\\{\\psi(\\alpha+J)-\\psi(\\alpha)\\}$ against",
  "$J$ on a logarithmic axis, where the curves are straight: the number of clusters grows",
  "like $\\alpha\\log J$, so ten times the data buys only $\\alpha\\log 10 \\approx 2.3\\alpha$",
  "more clusters. Deterministic; no simulation. Generated by code/R/09-figures.R."),
  draw_kalpha, w = 7.4, h = 4.2)

## ---- F-dpm-fit : representational capacity, on one dataset -------------
## Restored 2026-08-04 after review 012 removed it. The removal was right about
## the CLAIMS and wrong about the figure: the left panel is a representational
## point of the same class as F-flexible-g, and the right panel is retained only
## because the correct prior-versus-posterior comparison inverts what the first
## version asserted. Reads the cache from code/R/16-dpm-fit-artifact.R.
dpm_cache <- file.path(paths$tables, "F-dpm-fit-cache.rds")
if (file.exists(dpm_cache)) {
  draw_dpmfit <- function() {
    z <- readRDS(dpm_cache)
    op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.6, 0.8), cex.axis = .9)

    plot(NA, xlim = c(-3, 3), ylim = c(0, max(z$true, z$dpm_hi) * 1.05),
         xlab = expression(theta), ylab = "density",
         main = sprintf("What each prior can represent (%d persons, %d items)", z$P, z$I),
         cex.main = 0.95)
    polygon(c(z$grid, rev(z$grid)), c(z$dpm_lo, rev(z$dpm_hi)),
            col = adjustcolor(PAL[2], 0.18), border = NA)
    lines(z$grid, z$true, col = PAL[5], lwd = 3.2)
    lines(z$grid, z$dpm_mean, col = PAL[2], lwd = 2.4)
    lines(z$grid, z$nor_mean, col = PAL[1], lwd = 2.4, lty = 2)
    legend("topright", bty = "n", cex = .8, lwd = c(3.2, 2.4, 2.4),
           lty = c(1, 1, 2), col = c(PAL[5], PAL[2], PAL[1]),
           legend = c("generating G", "DPM posterior mean", "Gaussian model"))

    kmax <- 12L
    pri <- z$K_prior_pmf[1:kmax]; pos <- z$K_post_pmf[1:kmax]
    bp <- barplot(rbind(pri, pos), beside = TRUE, names.arg = 1:kmax,
                  col = c(adjustcolor(PAL[5], .55), PAL[3]), border = "white",
                  xlab = "occupied clusters K", ylab = "probability",
                  main = expression("Prior-predictive vs posterior for "*K))
    legend("topright", bty = "n", cex = .8, fill = c(adjustcolor(PAL[5], .55), PAL[3]),
           border = "white",
           legend = c(sprintf("prior-predictive (P(K=1) = %.2f)", z$K_prior_pmf[1]),
                      sprintf("posterior (P(K=1) = %.2f)", z$K_post_pmf[1])))
    par(op)
  }
  save_fig("F-dpm-fit", {
    z <- readRDS(dpm_cache)
    paste(
      "A Dirichlet process mixture and a Gaussian Rasch model, both item-centred, fitted",
      sprintf("to one simulated dataset of %d persons and %d items with a bimodal", z$P, z$I),
      "generating $G$. **This figure is about representational capacity, in the same sense",
      "as @fig-flexible-g: it shows what each prior *can* express, not how either performs.**",
      "No performance claim is made from it and none should be read out of it; the",
      "companion simulation study owns that question.",
      "**Left:** the generating density, the DPM posterior mean, and the Gaussian model's",
      "posterior mean. The DPM expresses two modes; the Gaussian family cannot express",
      "more than one at any parameter value. The shaded band is the pointwise 5th--95th",
      "percentile across posterior draws of the realized-partition mixture density — a",
      "posterior summary of that density, not a credible band for a Dirichlet-process",
      "functional. **Right:** the exact prior-predictive pmf of the occupied-cluster count",
      "$K$, obtained by integrating Antoniak's law over the $\\mathrm{Gamma}(1,3)$ prior on",
      sprintf("$\\alpha$, against its posterior. They differ by %.2f in total variation:", z$K_tv),
      sprintf("the prior places %.2f on a single cluster and the posterior places %.2f.",
              z$K_prior_pmf[1], z$K_post_pmf[1]),
      "The data move $K$ substantially. Note also that $K$ is the occupied-partition count",
      "at this sample size, not the order of a true mixture, and @prp-partial-id concerns",
      "functionals of $G$ rather than either. Seed 2026; regenerate with",
      "code/R/16-dpm-fit-artifact.R.")
  }, draw_dpmfit, w = 7.6, h = 4.2)
} else {
  cat("  F-dpm-fit              SKIPPED (run code/R/16-dpm-fit-artifact.R first)\n")
}

## ---- F-three-goals : the three ensembles, and what each is optimal for ----
## Deterministic: independent normal posteriors, everything by quadrature.
draw_three_goals <- function() {
  eta <- c(-1.6, -0.9, -0.4, -0.1, 0.2, 0.6, 1.1, 1.8)
  lam <- c(0.50, 0.40, 0.35, 0.30, 0.30, 0.35, 0.45, 0.60); K <- length(eta)
  g <- seq(-6, 6, length.out = 6001)
  Gbar <- vapply(g, function(t) mean(pnorm(t, eta, sqrt(lam))), numeric(1))
  Uhat <- approxfun(Gbar, g, ties = "ordered", rule = 2)((2 * (1:K) - 1) / (2 * K))
  Rbar <- vapply(seq_len(K), function(k) sum(vapply(seq_len(K), function(q)
    if (q == k) 1 else pnorm(0, eta[q] - eta[k], sqrt(lam[k] + lam[q])), numeric(1))),
    numeric(1))
  if (anyDuplicated(round(Rbar, 12)))
    stop("F-three-goals requires distinct expected ranks; exact ties need randomized refinement")
  gr <- Uhat[rank(Rbar, ties.method = "min")]
  a  <- sqrt(1 + mean(lam) / (sum((eta - mean(eta))^2) / (K - 1)))
  cb <- mean(eta) + a * (eta - mean(eta))
  op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.6, 0.8), cex.axis = .9, cex.main = .96)

  plot(g, Gbar, type = "l", lwd = 2.6, col = PAL[5], xlim = c(-3.2, 3.2),
       xlab = expression(t), ylab = expression(bar(G)[K](t)),
       main = expression(bar(G)[K](t)*" is a probability"))
  segments(-6, (2*(1:K)-1)/(2*K), Uhat, (2*(1:K)-1)/(2*K), col = "grey80", lty = 3)
  segments(Uhat, 0, Uhat, (2*(1:K)-1)/(2*K), col = PAL[3], lty = 3)
  points(Uhat, (2*(1:K)-1)/(2*K), pch = 16, col = PAL[3], cex = 1.1)
  points(0, mean(pnorm(0, eta, sqrt(lam))), pch = 4, cex = 1.5, lwd = 2.4, col = PAL[2])
  text(0.15, mean(pnorm(0, eta, sqrt(lam))) - 0.07, adj = 0, cex = .82, col = PAL[2],
       labels = sprintf("Gbar(0) = %.3f", mean(pnorm(0, eta, sqrt(lam)))))
  legend("topleft", bty = "n", cex = .8, lwd = c(2.6, NA), pch = c(NA, 16),
         col = c(PAL[5], PAL[3]),
         legend = c(expression(bar(G)[K]), expression("mass points "*hat(U)[j])))

  plot(NA, xlim = c(0.6, 3.4), ylim = range(c(eta, cb, gr)) + c(-.25, .25),
       xaxt = "n", xlab = "", ylab = expression(theta), main = "Three ensembles, same ranks")
  axis(1, at = 1:3, labels = c("PM", "CB", "GR"), cex.axis = 1.05)
  for (k in seq_len(K)) lines(1:3, c(eta[k], cb[k], gr[k]), col = "grey78")
  points(rep(1, K), eta, pch = 16, col = PAL[1], cex = 1.1)
  points(rep(2, K), cb,  pch = 16, col = PAL[3], cex = 1.1)
  points(rep(3, K), gr,  pch = 16, col = PAL[2], cex = 1.1)
  sv <- function(x) sum((x - mean(x))^2) / (K - 1)
  mtext(sprintf("sample variance %.2f / %.2f / %.2f, target %.2f",
                sv(eta), sv(cb), sv(gr), mean(lam) + sv(eta)), side = 1, line = 2.4, cex = .8)
  par(op)
}
save_fig("F-three-goals", paste(
  "**Left:** $\\bar G_K(t) = K^{-1}\\sum_k \\Pr(\\theta_k \\le t \\mid \\mathbf{Y})$ for eight",
  "units with independent normal posteriors. It is a **cumulative probability**, not a",
  "latent-trait estimate — the cross marks $\\bar G_K(0) = 0.476$, the estimated fraction of",
  "these eight people below zero. The triple-goal mass points $\\hat U_j =",
  "\\bar G_K^{-1}\\{(2j-1)/2K\\}$ are read off it, and *those* are on the trait scale.",
  "**Right:** the three ensembles. All induce the same ordering in this computed example;",
  "the unequal posterior variances mean Theorem 2's stochastic-order condition is not",
  "available as its justification. Constrained Bayes matches the target ensemble variance exactly,",
  "because that is what it is built to do; the triple-goal ensemble does not, because it",
  "matches the whole estimated EDF rather than its second moment. Deterministic; no",
  "simulation. Generated by code/R/09-figures.R."),
  draw_three_goals, w = 7.8, h = 4.3)

## ---- F-rank-reliability : matched-reliability rank recovery -------------
## Pairwise concordance for the common-item Rasch model: for two iid persons,
## P(scores correctly ordered) + 0.5 P(score tie), by midpoint-quantile
## quadrature over four full-support, unit-variance latent distributions.
rank_rel_fine <- rank_reliability_analysis(n = 800L)
rank_rel_coarse <- rank_reliability_analysis(n = 400L)
rank_rel_meta <- rank_reliability_summary(rank_rel_fine, rank_rel_coarse)
rank_rel_convergence <- transform(
  rank_rel_meta$convergence,
  absolute_wbar_difference = abs(wbar_fine - wbar_coarse),
  absolute_concordance_difference = abs(concordance_fine - concordance_coarse))
rank_rel_curve_cols <- c("shape", "items", "wbar", "concordance", "quadrature_nodes", "curve")
rank_rel_curves <- rbind(
  transform(rank_rel_fine$curves, curve = "design")[, rank_rel_curve_cols],
  transform(rank_rel_fine$matched, items = NA_integer_, quadrature_nodes = rank_rel_fine$n,
            curve = "matched")[, rank_rel_curve_cols])
save_figure_data(rank_rel_meta$summary, "F-rank-reliability-summary")
save_figure_data(rank_rel_convergence, "F-rank-reliability-convergence")
save_figure_data(rank_rel_curves, "F-rank-reliability-curves")
save_figure_data(rank_rel_fine$gaps, "F-rank-reliability-matched-gaps")

draw_rank_rel <- function() {
  curves <- rank_rel_fine$curves
  gaps <- rank_rel_fine$gaps
  near <- rank_rel_fine$near_ties
  op <- par(mfrow = c(1, 2), mar = c(4.3, 4.4, 2.6, 0.8), cex.axis = .9, cex.main = .96)

  plot(NA, xlim = range(curves$wbar), ylim = range(curves$concordance),
       xlab = expression(bar(w)), ylab = "pairwise rank concordance",
       main = "Reliability is the leading driver")
  for (k in seq_along(rank_shape_names)) {
    z <- curves[curves$shape == rank_shape_names[k], ]
    lines(z$wbar, z$concordance, col = PAL[k], lwd = 2.4, type = "b", pch = 16, cex = .55)
  }
  legend("topleft", bty = "n", cex = .76, lwd = 2.4,
         col = PAL[seq_along(rank_shape_names)], legend = rank_shape_names)

  plot(gaps$wbar, gaps$gap, type = "l", lwd = 2.6, col = PAL[2],
       xlab = expression("matched "*bar(w)), ylab = "spread across the four shapes",
       ylim = c(0, max(gaps$gap) * 1.18), main = "Shape gap peaks, then declines")
  imax <- which.max(gaps$gap)
  points(gaps$wbar[imax], gaps$gap[imax], pch = 16, col = PAL[2], cex = 1.0)
  abline(h = 0, col = "grey85")
  legend("topleft", bty = "n", cex = .74,
         legend = c("near-tie mass, P(|diff| < 0.25):",
                    paste0("  ", near$shape, ": ", sprintf("%.3f", near$near_tie_mass))))
  par(op)
}
save_fig("F-rank-reliability", paste(
  "Deterministic pairwise rank concordance for a common-item Rasch test under four",
  "full-support latent distributions standardized to variance 1; score ties receive half",
  "credit. **Left:** each shape's concordance is plotted against its own $\\bar w$ over",
  "tests from 6 through 180 items. Reliability is the leading driver, but shape does not",
  "drop out. **Right:** the cross-shape spread is calculated only after interpolation to a",
  "common $\\bar w$ grid; it reaches a finite-range peak and then declines, consistent with",
  "concordance tending to one for every continuous shape as information grows. The",
  "heavy-tailed curve is a unit-variance logistic distribution, not a truncated $t$.",
  "Midpoint-quantile quadrature uses 800 nodes and is checked against 400 nodes; numerical",
  "summaries and convergence receipts are frozen under tables/F-rank-reliability-*.rds.",
  "Generated by code/R/09-figures.R."),
  draw_rank_rel, w = 7.8, h = 4.3)
