## 22-figures-v2-concepts.R - concept diagrams added in v2.
## Box-and-arrow diagrams drawn in ggplot on a fixed 0-100 plane; no numbers
## from any analysis appear here except where a label is read from a frozen
## table, and each caption says so. Chapters embed; they never plot.

source("code/R/00-paths.R")
source("code/R/21-style-v2.R")
FIG <- paths$figures
dir.create(FIG, showWarnings = FALSE, recursive = TRUE)

## ---- F-estimand-map : three questions -> targets -> losses -> summaries ---
b <- rbind(
  box_row(16, 96, 26, 7, "What is this\nstudent's score?", fill = "#EFF4FA",
          colour = PAL[1], fontface = "bold"),
  box_row(50, 96, 26, 7, "Which five should\nget the intervention?", fill = "#FDF1E8",
          colour = PAL[2], fontface = "bold"),
  box_row(84, 96, 26, 7, "What fraction is\nbelow the benchmark?", fill = "#EBF6F1",
          colour = PAL[3], fontface = "bold"),

  box_row(16, 74, 26, 8, "each person's\nlatent trait"),
  box_row(50, 74, 26, 8, "the ranks\nwithin the class"),
  box_row(84, 74, 26, 8, "the realized trait\ndistribution of the class"),

  box_row(16, 52, 26, 8, "squared error,\nsummed over persons"),
  box_row(50, 52, 26, 8, "squared error\non ranks"),
  box_row(84, 52, 26, 8, "integrated squared\nerror on the EDF"),

  box_row(16, 29, 26, 8, "posterior mean\n(PM)", fill = "#EFF4FA", colour = PAL[1],
          fontface = "bold"),
  box_row(50, 29, 26, 8, "posterior expected\nranks", fill = "#FDF1E8", colour = PAL[2],
          fontface = "bold"),
  box_row(84, 29, 26, 8, "a distribution estimate,\nnot the PM histogram",
          fill = "#EBF6F1", colour = PAL[3], fontface = "bold"),

  box_row(50, 8, 92, 10,
          paste("No single set of person estimates is optimal for all three questions at once.",
                "Chapter 17 states this as a proposition;",
                "Chapters 18 and 19 build the repairs.", sep = "\n"),
          fill = "grey96", colour = INK2, size = 3.0, linetype = "22")
)
lab <- data.frame(
  x = 2.2, y = c(96, 74, 52, 29),
  label = c("Question", "Target", "Loss", "Bayes answer")
)
a <- rbind(
  arrow_row(16, 92.5, 16, 78.5), arrow_row(50, 92.5, 50, 78.5), arrow_row(84, 92.5, 84, 78.5),
  arrow_row(16, 70, 16, 56.5),   arrow_row(50, 70, 50, 56.5),   arrow_row(84, 70, 84, 56.5),
  arrow_row(16, 48, 16, 33.5),   arrow_row(50, 48, 50, 33.5),   arrow_row(84, 48, 84, 33.5)
)
p <- draw_diagram(b, a, xlim = c(-6, 101), ylim = c(2, 101)) +
  geom_text(data = lab, aes(x = x, y = y, label = label), angle = 90,
            colour = INK2, size = 2.9, fontface = "italic", family = "Helvetica")
save_fig2("F-estimand-map",
  paste("**Three questions, three estimation problems.** Each question a test's",
        "user asks names its own target, the target implies a loss, and the loss",
        "has its own Bayes answer; the columns do not collapse into one set of",
        "numbers. The left column is the individual-score problem that posterior",
        "means solve; the middle column is the ranking problem of @sec-ch20; the",
        "right column is the distribution problem that Part VI repairs, first by",
        "rescaling (@sec-ch18) and then by reconstruction (@sec-ch19). Layout",
        "only; no analysis output appears. Generated by code/R/22-figures-v2-concepts.R."),
  p, w = 8.2, h = 5.4)

## ---- F-flexible-tree : what must the analyst decide in advance? -----------
b <- rbind(
  box_row(50, 95, 62, 7, "Let the data determine G", fill = "grey96",
          colour = INK2, fontface = "bold"),

  box_row(13, 74, 21, 11, "Empirical\nhistogram", fill = "#EFF4FA", colour = PAL[1]),
  box_row(36, 74, 21, 11, "Ramsay and\nDavidian curves", fill = "#EFF4FA", colour = PAL[1]),
  box_row(59, 74, 21, 11, "Richer parametric\nfamilies", fill = "#EFF4FA", colour = PAL[1]),
  box_row(82, 74, 21, 11, "Finite mixtures\n(population K components)", fill = "#EFF4FA", colour = PAL[1],
          size = 2.8),

  box_row(13, 55, 21, 8, "grid location\nand resolution", size = 2.8, colour = INK2),
  box_row(36, 55, 21, 8, "the order or\ncap of the curve", size = 2.8, colour = INK2),
  box_row(59, 55, 21, 8, "the family\nitself", size = 2.8, colour = INK2),
  box_row(82, 55, 21, 8, "the population\ncomponent count K", size = 2.8, colour = INK2),

  box_row(29, 33, 38, 14,
          "Dirichlet process mixture:\npopulation K is infinite;\noccupied K_J is posterior and sample-size dependent;\nalpha must be chosen",
          fill = "#FDF1E8", colour = PAL[2], fontface = "bold", size = 2.6),
  box_row(73, 33, 38, 13,
          "Mixture of finite mixtures:\nan explicit prior on the\npopulation component count K",
          fill = "#EBF6F1", colour = PAL[3], size = 2.8),

  box_row(50, 10, 96, 11,
          paste("Every route trades one advance decision for another.",
                "The DP replaces a finite population-K choice with alpha; its posterior",
                "cluster count is occupied K_J for the observed sample, not population K.", sep = "\n"),
          fill = "grey96", colour = INK2, size = 3.0, linetype = "22")
)
a <- rbind(
  arrow_row(21, 91.5, 13, 80),  arrow_row(41, 91.5, 36, 80),
  arrow_row(59, 91.5, 59, 80),  arrow_row(79, 91.5, 82, 80),
  arrow_row(13, 68.5, 13, 59.5), arrow_row(36, 68.5, 36, 59.5),
  arrow_row(59, 68.5, 59, 59.5), arrow_row(82, 68.5, 82, 59.5),
  arrow_row(82, 51, 40, 39.5),  arrow_row(82, 51, 72, 39.5)
)
lab <- data.frame(x = 2.2, y = c(74, 55), label = c("Approach", "Decided in advance"))
p <- draw_diagram(b, a, xlim = c(-7, 101), ylim = c(4, 100)) +
  geom_text(data = lab, aes(x = x, y = y, label = label), angle = 90,
            colour = INK2, size = 2.9, fontface = "italic", family = "Helvetica")
save_fig2("F-flexible-tree",
  paste("**Flexible latent distributions, organized by the decision the analyst",
        "must still make in advance.** The top row is the shared aim; the second",
        "row lists the main routes of @sec-ch14; the third row names the choice",
        "each route leaves on the analyst's desk. Two Bayesian descendants of the",
        "finite-mixture route make two different component counts explicit. A",
        "Dirichlet process has infinitely many population atoms; its posterior",
        "count $K_J$ is the number occupied by the observed $J$ draws and therefore",
        "depends on sample size as well as the chosen concentration $\\alpha$",
        "(@sec-ch15). A mixture of finite mixtures instead places a prior directly",
        "on the finite population component count $K$ (Miller and Harrison 2018).",
        "Layout only; no analysis",
        "output appears. Generated by code/R/22-figures-v2-concepts.R."),
  p, w = 8.2, h = 5.6)

## ---- F-gr-pipeline : the triple-goal construction, step by step -----------
## Small worked example under the constant-error working model of ch. 11;
## seeded, illustrative. The point is the mechanics, not the values.
set.seed(1129)
N <- 12; K <- N
th_true <- sort(c(rnorm(6, -1, .4), rnorm(6, 1, .4)))
wbar <- 0.6
y <- th_true + rnorm(N, 0, sqrt(1 / wbar - 1))
pm <- wbar * y
## a stylized Ghat: the (2k-1)/2K quantile midpoints of a bimodal estimate;
## for illustration take Ghat = the true generating mixture
qs <- (2 * seq_len(K) - 1) / (2 * K)
gh <- function(p) {  ## quantile of equal mixture N(-1,.4^2), N(1,.4^2)
  sapply(p, function(pp) uniroot(function(x)
    0.5 * pnorm(x, -1, .4) + 0.5 * pnorm(x, 1, .4) - pp, c(-4, 4))$root)
}
mass <- gh(qs)
rk <- rank(pm)
gr <- mass[rk]
gr_map <- data.frame(pm = pm, gr = gr, rank = rank(pm),
                     direction = ifelse(gr > pm, "right", "left"))
stopifnot(all(gr != pm), any(gr_map$direction == "right"),
          any(gr_map$direction == "left"),
          all(sign(gr_map$gr - gr_map$pm) ==
              ifelse(gr_map$direction == "right", 1, -1)))

xs <- seq(-2.6, 2.6, length.out = 401)
Ghat <- 0.5 * pnorm(xs, -1, .4) + 0.5 * pnorm(xs, 1, .4)
pa <- ggplot() +
  geom_line(aes(xs, Ghat), colour = INK, linewidth = 0.6) +
  geom_segment(aes(x = mass, xend = mass, y = 0, yend = qs),
               colour = PAL[3], linewidth = 0.3, linetype = "22") +
  geom_point(aes(mass, qs), colour = PAL[3], size = 1.9) +
  labs(x = expression(theta), y = expression(hat(G)(theta)),
       subtitle = "Step 1 - cut the estimated distribution into K mass points\nat the midpoint quantiles (2k - 1)/2K") +
  theory_theme(10.5)
pb <- ggplot() +
  geom_segment(data = gr_map,
               aes(x = pm, xend = gr, y = rank, yend = rank),
               colour = "grey70", linewidth = 0.35,
               arrow = arrow(length = unit(1.4, "mm"), type = "closed")) +
  geom_point(data = gr_map, aes(pm, rank), colour = PAL[1], size = 1.9) +
  geom_point(data = gr_map, aes(gr, rank), colour = PAL[3], size = 1.9) +
  annotate("text", x = -2.25, y = 11.8, label = "posterior means",
           colour = PAL[1], size = 3, hjust = 0, family = "Helvetica") +
  annotate("text", x = -2.25, y = 10.9, label = "triple-goal estimates",
           colour = PAL[3], size = 3, hjust = 0, family = "Helvetica") +
  labs(x = expression(hat(theta)), y = "rank",
       subtitle = "Step 2 - keep each person's estimated rank,\nbut report the mass point that rank points at") +
  theory_theme(10.5)
p <- pa + pb + plot_annotation(tag_levels = "a", tag_prefix = "(", tag_suffix = ")")
save_fig2("F-gr-pipeline",
  paste("**The triple-goal construction in two moves.** (a) The estimated",
        "distribution is reduced to K mass points at its midpoint quantiles,",
        "so the reported ensemble carries the estimated shape by construction.",
        "(b) Each person keeps the rank estimated from the posterior and is",
        "assigned the mass point that rank selects. Every arrow starts at a",
        "posterior mean and its arrowhead ends at the triple-goal estimate:",
        "right-pointing arrows have GR greater than PM, and left-pointing arrows",
        "have GR less than PM. The mapping stretches the compressed ensemble back",
        "onto the distribution's support without reordering anyone.",
        "Worked on a seeded twelve-person illustration under the constant-error",
        "working model of @sec-ch11, with the estimated distribution taken to be",
        "the generating mixture for display; nothing quantitative rests on it.",
        "Generated by code/R/22-figures-v2-concepts.R."),
  p, w = 8.6, h = 4.0)

## ---- F-ident-2pl : what pins location and scale, Rasch versus 2PL ---------
sh <- data.frame(x = c(8, 92), y = c(50, 50))
pa <- ggplot() +
  geom_hline(yintercept = 1, colour = PAL[1], linewidth = 0.9) +
  annotate("point", x = 0, y = 1, colour = INK, size = 2.6) +
  annotate("text", x = 0, y = 1.28, label = "one location constraint\npicks the point",
           size = 2.9, colour = INK, family = "Helvetica", lineheight = 1) +
  annotate("text", x = 1.05, y = 0.83, label = "equivalent structures:\nshift persons and items together",
           size = 2.9, colour = PAL[1], family = "Helvetica", lineheight = 1) +
  scale_x_continuous(limits = c(-2.6, 2.6),
                     name = "location shift  c") +
  scale_y_continuous(limits = c(0.3, 2.1), trans = "log2",
                     name = "common rescaling  a") +
  labs(subtitle = "Rasch: discriminations fixed at one\nleave no rescaling freedom") +
  theory_theme(10.5)
pb <- ggplot() +
  annotate("rect", xmin = -2.6, xmax = 2.6, ymin = 0.3, ymax = 2.1,
           fill = "#FDF1E8", alpha = 0.55) +
  geom_hline(yintercept = 1, colour = INK2, linewidth = 0.35, linetype = "22") +
  geom_vline(xintercept = 0, colour = INK2, linewidth = 0.35, linetype = "22") +
  annotate("point", x = 0, y = 1, colour = INK, size = 2.6) +
  annotate("text", x = 0.05, y = 1.32, hjust = 0,
           label = "two constraints pick the point:\nmean difficulty zero,\nmean log discrimination zero",
           size = 2.9, colour = INK, family = "Helvetica", lineheight = 1.02) +
  annotate("text", x = -2.45, y = 0.37, hjust = 0,
           label = "every (c, a) is an equivalent structure: divide the\ndiscriminations by a, rescale and shift persons to match",
           size = 2.9, colour = PAL[2], family = "Helvetica", lineheight = 1.02) +
  scale_x_continuous(limits = c(-2.6, 2.6), name = "location shift  c") +
  scale_y_continuous(limits = c(0.3, 2.1), trans = "log2",
                     name = "common rescaling  a") +
  labs(subtitle = "2PL: rescaling moves into the discriminations,\nso the scale must be pinned as well") +
  theory_theme(10.5)
p <- pa + pb + plot_annotation(tag_levels = "a", tag_prefix = "(", tag_suffix = ")")
save_fig2("F-ident-2pl",
  paste("**The indeterminacy that must be restricted, Rasch versus 2PL.** Axes",
        "index the transformations that leave the likelihood unchanged: shifting",
        "persons and items together (horizontal) and rescaling the latent metric",
        "while compensating in the discriminations (vertical). (a) Under the",
        "Rasch model the discriminations are fixed at one, so only the shift",
        "survives and a single location constraint identifies the structure",
        "(@sec-ch04). (b) Under the 2PL the whole plane is an orbit of equivalent",
        "structures, and the software of this programme pins it with two",
        "constraints, mean difficulty zero and mean log discrimination zero",
        "(@sec-ch26); fixing the variance of G instead pins the same axis a",
        "different way. Conceptual layout; no analysis output appears. Generated",
        "by code/R/22-figures-v2-concepts.R."),
  p, w = 8.6, h = 4.1)

cat("concept figures complete\n")
